parameters:
#    stems_poll.example.class: Stems\PollBundle\Example

services:
#    stems_poll.example:
#        class: %stems_poll.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
